["cryptopp_md5.cc"] # no need to install those env in CI
ignore = true

["cryptopp_sha256.cc"] # no need to install those env in CI
ignore = true

["cryptopp_sha512.cc"] # no need to install those env in CI
ignore = true

["ossl_evp.cc"] # no need to install those env in CI
ignore = true

["ossl_md5.cc"] # no need to install those env in CI
ignore = true

["ossl_sha1.cc"] # no need to install those env in CI
ignore = true

["ossl_sha256.cc"] # no need to install those env in CI
ignore = true

["ossl_sha512.cc"] # no need to install those env in CI
ignore = true

["native_hash_file.cc"] # no need to install those env in CI
ignore = true

["sha1.cc"] # deprecated algorithm. only for examples
will_fail = "compiletime"

["md5.cc"] # deprecated algorithm. only for examples
will_fail = "compiletime"

["crc32.cc"] # TODO: CI runtime failed. why?
ignore = true

["sha256.cc"] # TODO: CI runtime failed. why?
ignore = true

["sha512.cc"] # TODO: CI runtime failed. why?
ignore = true
