["dijkstra_optimize.cc"] # TODO: CI runtime failed. why?
ignore = true

["dijkstra.cc"] # TODO: CI runtime failed. why?
ignore = true

["dijkstra_optimize_fastio.cc"] # TODO: CI runtime failed. why?
ignore = true

["dijkstra_optimize_fastio_unchecked.cc"] # TODO: CI runtime failed. why?
ignore = true
